Update attachment endpoint
swimlane/swimlane-python pull request #152
Opened 2022-12-05 22:59 UTC by lisa-reynolds

Use non-deprecated attachment download endpoint

2022-12-06 14:49 UTC, parayacr requested changes

2022-12-06 14:49 UTC, parayacr commented on swimlane/core/resources/attachment.py
> +            'attachment/{}/{}/{}'.format(self.record_id, self.field_id, self.file_id),
I think you missed the `download` in the path.

2022-12-06 15:14 UTC, parayacr commented on swimlane/core/resources/attachment.py
> +            'attachment/{}/{}/{}'.format(self.record_id, self.field_id, self.file_id),
Gotcha. Thank you.

2022-12-06 15:15 UTC, parayacr approved these changes

2022-12-07 14:09 UTC, tanner-lewis approved these changes

2022-12-07 15:59 UTC, merged