Adding examples for the text fields
swimlane/swimlane-python pull request #155
Opened 2022-12-15 14:57 UTC by daniel-hume

Adding valid values as examples to the textfield documentation

2022-12-15 15:04 UTC, jeanmurillo95 approved these changes
Approved

2022-12-15 16:28 UTC, PeggyZimmerman requested changes
One minor request for you, Daniel.

2022-12-15 16:28 UTC, PeggyZimmerman commented on docs/examples/fields.rst
> +Not all the types are supported, here is a list of examples of valid values:
```suggestion
Not all types are supported. Here are some examples of valid values:
```

2022-12-19 17:23 UTC, danguloa approved these changes

2022-12-19 17:29 UTC, merged